version: '3.8'
services:
  db:
    image: postgres:15
    container_name: booking_db
    command: -p 5442
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev


  redis:
    image: redis:7
    container_name: booking_redis

  
  booking:
      build:
        context: .
      container_name: booking_app
      env_file:
        - .env-non-dev
      depends_on:
        - db
        - redis
      command: ["/booking_app/docker/app.sh"]
      ports:
        - 8080:8000


  celery:
    build:
      context: .
    container_name: booking_celery
    env_file:
      - .env-non-dev
    command: ["/booking_app/docker/celery.sh", "celery"]
    depends_on:
      - redis
  
  celery_beat:
    build:
      context: . 
    container_name: booking_celery_beat
    command: ["/booking_app/docker/celery.sh", "celery_beat"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis


  flower:
    build:
      context: .
    container_name: booking_flower
    env_file:
      - .env-non-dev
    command: ["/booking_app/docker/celery.sh", "flower"]
    ports:
      - 5555:5555
    depends_on:
      - redis

volumes:
  postgresdata: